package com.example.demo.Model;

public class Video {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.id
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.img
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.type
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.href
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    private String href;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.title
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.id
     *
     * @return the value of video.id
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.id
     *
     * @param id the value for video.id
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.img
     *
     * @return the value of video.img
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.img
     *
     * @param img the value for video.img
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.type
     *
     * @return the value of video.type
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.type
     *
     * @param type the value for video.type
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.href
     *
     * @return the value of video.href
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    public String getHref() {
        return href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.href
     *
     * @param href the value for video.href
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    public void setHref(String href) {
        this.href = href == null ? null : href.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.title
     *
     * @return the value of video.title
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.title
     *
     * @param title the value for video.title
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }
}