package com.example.demo.Model;

public class Videolist {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videolist.id
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videolist.listid
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    private String listid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videolist.number
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videolist.href
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    private String href;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videolist.id
     *
     * @return the value of videolist.id
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videolist.id
     *
     * @param id the value for videolist.id
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videolist.listid
     *
     * @return the value of videolist.listid
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    public String getListid() {
        return listid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videolist.listid
     *
     * @param listid the value for videolist.listid
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    public void setListid(String listid) {
        this.listid = listid == null ? null : listid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videolist.number
     *
     * @return the value of videolist.number
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videolist.number
     *
     * @param number the value for videolist.number
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videolist.href
     *
     * @return the value of videolist.href
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    public String getHref() {
        return href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videolist.href
     *
     * @param href the value for videolist.href
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    public void setHref(String href) {
        this.href = href == null ? null : href.trim();
    }
}