package com.example.demo.Mapper;

import com.example.demo.Model.Videolist;
import com.example.demo.Model.VideolistExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface VideolistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videolist
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    long countByExample(VideolistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videolist
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    int deleteByExample(VideolistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videolist
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videolist
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    int insert(Videolist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videolist
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    int insertSelective(Videolist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videolist
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    List<Videolist> selectByExampleWithRowbounds(VideolistExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videolist
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    List<Videolist> selectByExample(VideolistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videolist
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    Videolist selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videolist
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    int updateByExampleSelective(@Param("record") Videolist record, @Param("example") VideolistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videolist
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    int updateByExample(@Param("record") Videolist record, @Param("example") VideolistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videolist
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    int updateByPrimaryKeySelective(Videolist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videolist
     *
     * @mbg.generated Mon Nov 29 23:46:02 CST 2021
     */
    int updateByPrimaryKey(Videolist record);
}